
unused = "#79e11a"

[mytheme]
  gray1 = "#464752"
  gray2 = "#565761"
  gray3 = "#b6b6b2"
  gray4 = "#ccccc7"
  black = "#282a36"
  blue = "#6272a4"
  cyan = "#8be9fd"
  green = "#50fa7b"
  magenta = "#ff79c6"
  orange = "#ffb86c"
  purple = "#bd93f9"
  red = "#ff5555"
  white = "#f8f8f2"
  yellow = "#f1fa8c"

[dark]
  button = ["mytheme.black","mytheme.gray3"]
  button-focus = ["mytheme.black","mytheme.magenta"]
  button-selected = ["mytheme.white","mytheme.gray3"]
  cmdline = ["mytheme.black","mytheme.yellow"]
  cmdline-button = ["mytheme.yellow","mytheme.black"]
  cmdline-border = ["mytheme.black","mytheme.yellow"]
  copy-mode = ["mytheme.black","mytheme.yellow"]
  copy-mode-alt = ["mytheme.yellow","mytheme.black"]
  copy-mode-label = ["mytheme.white","mytheme.red"]
  current-capture = ["mytheme.white","themes.unused"]
  dialog = ["mytheme.black","mytheme.yellow"]
  dialog-button = ["mytheme.yellow","mytheme.black"]
  default = ["mytheme.white","mytheme.black"]
  filter-empty = ["mytheme.black","mytheme.cyan"]
  filter-intermediate = ["mytheme.black","mytheme.orange"]
  filter-invalid = ["mytheme.black","mytheme.red"]
  filter-menu = ["mytheme.white","mytheme.black"]
  filter-valid = ["mytheme.black","mytheme.green"]
  hex-byte-selected = ["mytheme.white","mytheme.purple"]
  hex-byte-unselected = ["mytheme.white","mytheme.black"]
  hex-field-selected = ["mytheme.black","mytheme.cyan"]
  hex-field-unselected = ["mytheme.black","mytheme.white"]
  hex-interval-selected = ["mytheme.white","mytheme.gray2"]
  hex-interval-unselected = ["mytheme.white","mytheme.gray1"]
  hex-layer-selected = ["mytheme.white","mytheme.gray2"]
  hex-layer-unselected = ["mytheme.white","mytheme.gray1"]
  packet-list-cell-focus = ["mytheme.white","mytheme.purple"]
  packet-list-cell-selected = ["mytheme.white","mytheme.gray2"]
  packet-list-row-focus = ["mytheme.white","mytheme.cyan"]
  packet-list-row-selected = ["mytheme.white","mytheme.gray1"]
  packet-struct-focus = ["mytheme.black","mytheme.cyan"]
  packet-struct-selected = ["mytheme.black","mytheme.gray2"]
  progress-complete = ["mytheme.white","mytheme.purple"]
  progress-default = ["mytheme.white","mytheme.black"]
  progress-spinner = ["mytheme.yellow","mytheme.purple"]
  spinner = ["mytheme.yellow","mytheme.black"]
  stream-client = ["mytheme.black","mytheme.red"]
  stream-match = ["mytheme.black","mytheme.yellow"]
  stream-search = ["mytheme.black","mytheme.white"]
  stream-server = ["mytheme.white","mytheme.blue"]
  title = ["mytheme.red","unused"]

[light]
  button = ["mytheme.black","mytheme.white"]
  button-focus = ["mytheme.black","mytheme.purple"]
  button-selected = ["mytheme.black","mytheme.gray3"]
  cmdline = ["mytheme.black","mytheme.yellow"]
  cmdline-button = ["mytheme.yellow","mytheme.black"]
  cmdline-border = ["mytheme.black","mytheme.yellow"]
  copy-mode = ["mytheme.white","mytheme.yellow"]
  copy-mode-alt = ["mytheme.yellow","mytheme.white"]
  copy-mode-label = ["mytheme.black","mytheme.red"]
  current-capture = ["mytheme.black","unused"]
  dialog = ["mytheme.black","mytheme.yellow"]
  dialog-button = ["mytheme.yellow","mytheme.black"]
  default = ["mytheme.black","mytheme.white"]
  filter-empty = ["mytheme.black","mytheme.cyan"]
  filter-intermediate = ["mytheme.black","mytheme.orange"]
  filter-invalid = ["mytheme.black","mytheme.red"]
  filter-menu = ["mytheme.black","mytheme.white"]
  filter-valid = ["mytheme.black","mytheme.green"]
  hex-byte-selected = ["mytheme.white","mytheme.purple"]
  hex-byte-unselected = ["mytheme.black","mytheme.white"]
  hex-field-selected = ["mytheme.black","mytheme.cyan"]
  hex-field-unselected = ["mytheme.black","mytheme.gray2"]
  hex-interval-selected = ["mytheme.white","mytheme.gray2"]
  hex-interval-unselected = ["mytheme.black","mytheme.gray4"]
  hex-layer-selected = ["mytheme.white","mytheme.gray2"]
  hex-layer-unselected = ["mytheme.black","mytheme.gray4"]
  packet-list-cell-focus = ["mytheme.white","mytheme.purple"]
  packet-list-cell-selected = ["mytheme.black","mytheme.gray3"]
  packet-list-row-focus = ["mytheme.white","mytheme.cyan"]
  packet-list-row-selected = ["mytheme.black","mytheme.gray4"]
  packet-struct-focus = ["mytheme.black","mytheme.cyan"]
  packet-struct-selected = ["mytheme.black","mytheme.gray4"]
  progress-complete = ["mytheme.white","mytheme.purple"]
  progress-default = ["mytheme.white","mytheme.black"]
  progress-spinner = ["mytheme.yellow","mytheme.black"]
  spinner = ["mytheme.yellow","mytheme.white"]
  stream-client = ["mytheme.white","mytheme.red"]
  stream-match = ["mytheme.white","mytheme.yellow"]
  stream-search = ["mytheme.white","mytheme.black"]
  stream-server = ["mytheme.white","mytheme.blue"]
  title = ["mytheme.red","unused"]
